runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /\.well-known/acme-challenge/.*
  script: letsencrypt.app
  secure: never
- url: /.*
  script: main.app
  secure: always
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
- ^src$

# TODO: List any other App Engine SDK libs you may need here.